package com.lafuente.sap.dao;

/**
 *
 * @author GUIDO CACERES PINTO
 */
public enum SPQuery {

    LIST_CLIENTES("NOVAGEL.ZF_GEL_GBAGE(?,?,?)"),
    LIST_RESERVAS("NOVAGEL.ZP_GEL_ILMCA(?,?)"),
    LIST_RESERVAS_POR_PAGAR("NOVAGEL.ZP_GEL_ILMCA_PAGOWEB(?,?,?)"),
    LIST_RESERVAS_CUOTAS("NOVAGEL.ZP_GEL_ILPPG_RESERVA(?,?)"),
    LIST_CONTRATOS("NOVAGEL.ZP_GEL_ILMPR(?,?)"),
    LIST_CONTRATOS_ACTIVOS("NOVAGEL.ZF_GEL_VISITAS_LOTES_CONTRATO_CLIENTE(?,?)"),
    LIST_CONTRATOS_POR_PAGAR("NOVAGEL.ZP_GEL_ILMPR_PAGOWEB(?,?,?)"),
    LIST_CONTRATOS_CUOTAS("NOVAGEL.ZP_GEL_ILPPG_CONTRATO(?,?)"),
    VOUCHER_RESERVA("NOVAGEL.ZP_GEL_VOUCHER_RESERVA(?,?)"),
    VOUCHER_CONTRATO("NOVAGEL.ZP_GEL_VOUCHER_CONTRATO(?,?,?)"),
    GET_LOTE("NOVAGEL.ZP_DEMO_PLAZOS_MODAL2(?,?)"),
    
    FORMAS_DE_PAGO("NOVAGEL.ZP_GEL_PLAZOS_MAX(?)"),
    SIMULADOR_ALCONTADO("NOVAGEL.ZP_PLAZO_CONTRATO(?,?)"),
    SIMULADOR_APLAZOS_HEADER("NOVAGEL.ZP_DEMO_PLAZOS_CAB(?,?,?,?,?)"),
    SIMULADOR_APLAZOS_DETAIL("NOVAGEL.ZP_DEMO_PLAZOS_CAB_DET(?,?,?,?,?)"),
    
    DIAS_HABILES_VACACION("NOVAGEL.ZP_GEL_DIAS_VACACIONES(?,?,?,?,?)"), 
    DATOS_EMPLEADO("NOVAGEL.ZP_GEL_EMPLEADO(?)"),
    LIST_EMPRESAS("NOVAGEL.ZP_GEL_EMPRESA(?)"), 
    DIAS_FESTIVOS("NOVAGEL.ZP_GEL_DIA_FESTIVO(?,?,?,?)"),;

    private final String consulta;

    private SPQuery(String consulta) {
        this.consulta = consulta;
    }

    String consulta() {
        return consulta;
    }

}
